build:
  environment:
    php:
      version: '7.1'
      ini:
        'date.timezone': 'Asia/Tokyo'
  tests:
    override:
      - command: composer test
        coverage:
          file: report/coverage.clover
          format: php-clover
  project_setup:
    before:
      - command: php -dalways_populate_raw_post_data=-1 -ddisplay_errors=stderr -S localhost:8000
        background: true

filter:
  excluded_paths:
    - tests/*

tools:
  php_sim: true
  php_pdepend: true
  php_analyzer: true

checks:
  php:
    verify_property_names: false
    verify_access_scope_valid: false
