language: php
php:
  - '7.3'
  - '7.2'

before_install:
  - 'find src -type f -name *.php | xargs php -nl'
  - 'php -ddisplay_errors=stderr -S localhost:8000 > /tmp/server.log 2>&1 &'

install:
  - composer install

script:
  - composer test

after_script:
  - cat /tmp/server.log

branches:
  only: [ master ]

notifications:
  email: false
