language: php
php:
  - '7.1'
  - '7.0'
  - '5.6'
  - '5.3'

before_install:
  - 'find src -type f -name *.php | xargs php -nl'
  - '[[ "$TRAVIS_PHP_VERSION" == "5.3" ]] || php -dalways_populate_raw_post_data=-1 -ddisplay_errors=stderr -S localhost:8000 > /tmp/server.log 2>&1 &'

install:
  - composer install

script:
  - '[[ "$TRAVIS_PHP_VERSION" == "5.3" ]] || composer test'

after_script:
  - cat /tmp/server.log

branches:
  only: [ master ]

notifications:
  email: false
